public enum GscEffect {

    NormalHit,
    Sleep,
    PoisonHit,
    LeechHit,
    BurnHit,
    FreezeHit,
    ParalyzeHit,
    Selfdestruct,
    DreamEater,
    MirrorMove,
    AttackUp,
    DefenseUp,
    SpeedUp,
    SpAtkUp,
    SpDefUp,
    AccuracyUp,
    EvasionUp,
    AlwaysHit,
    AttackDown,
    DefenseDown,
    SpeedDown,
    SpAtkDown,
    SpDefDown,
    AccuracyDown,
    EvasionDown,
    ResetStats,
    Bide,
    Rampage,
    ForceSwitch,
    MultiHit,
    Conversion,
    FlinchHit,
    Heal,
    Toxic,
    PayDay,
    LightScreen,
    TriAttack,
    Unused25,
    Ohko,
    RazorWind,
    SuperFang,
    StaticDamage,
    TrapTarget,
    Unused2b,
    DoubleHit,
    JumpKick,
    Mist,
    FocusEnergy,
    RecoilHit,
    Confuse,
    AttackUp2,
    DefenseUp2,
    SpeedUp2,
    SpAtkUp2,
    SpDefUp2,
    AccuracyUp2,
    EvasionUp2,
    Transform,
    AttackDown2,
    DefenseDown2,
    SpeedDown2,
    SpAtkDown2,
    SpDefDown2,
    AccuracyDown2,
    EvasionDown2,
    Reflect,
    Poison,
    Paralyze,
    AttackDownHit,
    DefenseDownHit,
    SpeedDownHit,
    SpAtkDownHit,
    SpDefDownHit,
    AccuracyDownHit,
    EvasionDownHit,
    SkyAttack,
    ConfuseHit,
    PoisonMultiHit,
    Unused4e,
    Substitute,
    HyperBeam,
    Rage,
    Mimic,
    Metronome,
    LeechSeed,
    Splash,
    Disable,
    LevelDamage,
    Psywave,
    Counter,
    Encore,
    PainSplit,
    Snore,
    Conversion2,
    LockOn,
    Sketch,
    DefrostOpponent,
    SleepTalk,
    DestinyBond,
    Reversal,
    Spite,
    FalseSwipe,
    HealBell,
    PriorityHit,
    TripleKick,
    Thief,
    MeanLook,
    Nightmare,
    FlameWheel,
    Curse,
    Unused6e,
    Protect,
    Spikes,
    Foresight,
    PerishSong,
    Sandstorm,
    Endure,
    Rollout,
    Swagger,
    FuryCutter,
    Attract,
    Return,
    Present,
    Frustration,
    Safeguard,
    SacredFire,
    Magnitude,
    BatonPass,
    Pursuit,
    RapidSpin,
    Unused82,
    Unused83,
    MorningSun,
    Synthesis,
    Moonlight,
    HiddenPower,
    RainDance,
    SunnyDay,
    DefenseUpHit,
    AttackUpHit,
    AllUpHit,
    FakeOut,
    BellyDrum,
    PsychUp,
    MirrorCoat,
    SkullBash,
    Twister,
    Earthquake,
    FutureSight,
    Gust,
    Stomp,
    Solarbeam,
    Thunder,
    Teleport,
    BeatUp,
    Fly,
    DefenseCurl
}

public class GscMove : ROMObject {

    public Gsc Game;
    public GscEffect Effect;
    public byte Power;
    public GscType Type;
    public byte Accuracy;
    public byte PP;
    public byte EffectChance;

    public GscMove(Gsc game, ReadStream data, ReadStream name) {
        Game = game;
        Name = game.Charmap.Decode(name.Until(Charmap.Terminator));
        Id = data.u8();
        Effect = (GscEffect) data.u8();
        Power = data.u8();
        Type = (GscType) data.u8();
        Accuracy = data.u8();
        PP = data.u8();
        EffectChance = data.u8();
    }
}